# Generated by Django 4.1.4 on 2023-01-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='crate_energy_level',
            field=models.IntegerField(choices=[('one', '-'), ('two', '1'), ('three', '2'), ('four', '3'), ('five', '4'), ('six', '5'), ('seven', '6')], default=1),
        ),
    ]
