# Generated by Django 4.1.4 on 2023-01-12 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_alter_memberprofile_library'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberProfile',
            new_name='Profile',
        ),
    ]
