# Generated by Django 4.1.4 on 2023-01-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_vinylcolours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VinylColours',
            new_name='VinylColour',
        ),
    ]
