# Generated by Django 4.1.4 on 2023-01-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_vinylcolours_vinylcolour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinylcolour',
            options={'ordering': ['color']},
        ),
    ]
