# Generated by Django 4.1.4 on 2023-01-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_vinylcolour_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='crate_genre',
            field=models.CharField(choices=[('-', '-'), ('DNB', 'DNB'), ('Jungle 94-00', 'Jungle 94-00'), ('Jungle 10-', 'Jungle 10-'), ('Dubstep', 'Dubstep'), ('Grime', 'Grime'), ('Liquid DNB', 'Liquid DNB'), ('NeuroFunk 04-', 'NeuroFunk 04-'), ('Neurofunk 98-03', 'NeuroFunk 98-03'), ('Minimal DNB', 'Minimal DNB'), ('Halftime', 'Halftime')], default='DNB', max_length=50),
        ),
    ]
