# Generated by Django 4.1.4 on 2023-01-14 06:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vinylLibrary', '0022_rename_library_crate_issuecrate_library_sub_crate'),
        ('management', '0013_alter_crate_crate_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Member',
        ),
    ]
