# Generated by Django 4.1.4 on 2023-01-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_profile_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
