# Generated by Django 4.1.4 on 2023-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='crate_vibe',
            field=models.CharField(choices=[('-', '-'), ('Y', 'Yellow'), ('B', 'Blue'), ('R', 'Red'), ('G', 'Green')], default='Red', max_length=20),
        ),
    ]
