# Generated by Django 4.1.4 on 2023-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['vibe'],
            },
        ),
    ]
