# Generated by Django 4.1.4 on 2023-01-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_energylevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crate',
            old_name='crate_energy_level',
            new_name='crate_energy_levels',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='crate_genre',
            new_name='crate_genres',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='crate_vibe',
            new_name='crate_vibes',
        ),
    ]
