# Generated by Django 4.1.4 on 2023-01-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_rename_crate_energy_level_crate_crate_energy_levels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crate',
            old_name='crate_energy_levels',
            new_name='crate_energy_level',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='crate_genres',
            new_name='crate_genre',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='crate_vibes',
            new_name='crate_vibe',
        ),
    ]
