# Generated by Django 4.1.4 on 2023-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_rename_crate_energy_levels_crate_crate_energy_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.AlterField(
            model_name='crate',
            name='crate_energy_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='crate',
            name='crate_genre',
            field=models.CharField(choices=[('DNB', 'DNB'), ('Jungle 94-00', 'Jungle 94-00'), ('Jungle 10-', 'Jungle 10-'), ('Dubstep', 'Dubstep'), ('Grime', 'Grime'), ('Liquid DNB', 'Liquid DNB'), ('Neurofunk 04-', 'NeuroFunk 04-'), ('Neurofunk 98-03', 'NeuroFunk 98-03'), ('Minimal DNB', 'Minimal DNB'), ('Halftime', 'Halftime'), ('Eclectic', 'Eclectic')], default='DNB', max_length=50),
        ),
        migrations.AlterField(
            model_name='crate',
            name='crate_vibe',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green')], default='Red', max_length=20),
        ),
    ]
