# Generated by Django 4.1.4 on 2023-01-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
    ]
