# Generated by Django 4.1.4 on 2023-01-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_delete_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crate',
            old_name='crate_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='crate_energy_level',
            new_name='energy_level',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='crate_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='crate_mix',
            new_name='mix',
        ),
        migrations.RenameField(
            model_name='crate',
            old_name='crate_vibe',
            new_name='vibe',
        ),
    ]
