# Generated by Django 4.1.4 on 2023-01-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_rename_crate_description_crate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crate',
            name='genre',
            field=models.CharField(blank=True, choices=[('DNB', 'DNB'), ('Jungle 94-00', 'Jungle 94-00'), ('Jungle 10-', 'Jungle 10-'), ('Dubstep', 'Dubstep'), ('Grime', 'Grime'), ('Liquid DNB', 'Liquid DNB'), ('Neurofunk 04-', 'NeuroFunk 04-'), ('Neurofunk 98-03', 'NeuroFunk 98-03'), ('Minimal DNB', 'Minimal DNB'), ('Halftime', 'Halftime'), ('Eclectic', 'Eclectic')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crate',
            name='vibe',
            field=models.CharField(blank=True, choices=[('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green')], max_length=20, null=True),
        ),
    ]
