# Generated by Django 4.1.4 on 2023-01-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_alter_crate_energy_level_alter_crate_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='energy_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crate',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crate',
            name='vibe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
