# Generated by Django 4.1.4 on 2023-01-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_alter_crate_energy_level_alter_crate_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrateVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['variation'],
            },
        ),
    ]
