# Generated by Django 4.1.4 on 2023-01-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_cratevariations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrateVariations',
            new_name='CrateVariation',
        ),
    ]
