# Generated by Django 4.1.4 on 2023-01-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_vinylplatesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VinylReleaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_type', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['release_type'],
            },
        ),
        migrations.CreateModel(
            name='VinylSleeveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['sleeve'],
            },
        ),
        migrations.AlterModelOptions(
            name='vinylplatesize',
            options={},
        ),
    ]
