# Generated by Django 4.1.4 on 2023-01-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_vinylcondition_vinylreleasetype_vinylsleevetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='genre',
            field=models.CharField(blank=True, choices=[('DNB', 'DNB'), ('Jungle 94-00', 'Jungle 94-00'), ('Jungle 10-', 'Jungle 10-'), ('Dubstep', 'Dubstep'), ('Grime', 'Grime'), ('DNB Liquid', 'DNB Liquid'), ('Neurofunk 04-', 'NeuroFunk 04-'), ('Neurofunk 98-03', 'NeuroFunk 98-03'), ('DNB Minimal', 'DNB Minimal'), ('Halftime', 'Halftime'), ('Eclectic', 'Eclectic')], max_length=50, null=True),
        ),
    ]
