# Generated by Django 4.1.4 on 2023-01-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_alter_crate_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrateVariation',
            new_name='CrateType',
        ),
    ]
