# Generated by Django 4.1.4 on 2023-01-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0042_remove_salevinyl_library_and_more'),
        ('management', '0036_rename_cratevariation_cratetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopItem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
