# Generated by Django 4.1.4 on 2023-01-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_delete_shopitem_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
    ]
