# Generated by Django 4.1.4 on 2023-01-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('shipping_cost_to_NZ', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
