# Generated by Django 4.1.4 on 2023-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_vinyldistributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyldistributor',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
