# Generated by Django 4.1.4 on 2023-01-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_alter_vinyldistributor_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=100)),
                ('shipping_cost_destination_currency', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
