# Generated by Django 4.1.4 on 2023-01-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_vinylshipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyldistributor',
            name='shipping_cost_to_NZ',
        ),
    ]
