# Generated by Django 4.1.4 on 2023-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_remove_vinyldistributor_shipping_cost_to_nz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='genre',
            field=models.CharField(blank=True, choices=[('DnB', 'DnB'), ('Jungle 94-00', 'Jungle 94-00'), ('Jungle 10-', 'Jungle 10-'), ('Dubstep', 'Dubstep'), ('Grime', 'Grime'), ('DnB Liquid', 'DnB Liquid'), ('Neurofunk 04-', 'NeuroFunk 04-'), ('Neurofunk 98-03', 'NeuroFunk 98-03'), ('DnB Minimal', 'DnB Minimal'), ('Halftime', 'Halftime'), ('Eclectic', 'Eclectic')], max_length=50, null=True),
        ),
    ]
