# Generated by Django 4.1.4 on 2023-02-11 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0043_alter_crate_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='libarian',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_of_the_librarian', to=settings.AUTH_USER_MODEL),
        ),
    ]
