# Generated by Django 4.1.4 on 2023-02-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_alter_library_libarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='members',
        ),
    ]
