# Generated by Django 4.1.4 on 2023-02-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_remove_library_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='libarian',
            new_name='librarian',
        ),
    ]
