# Generated by Django 4.1.4 on 2023-02-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_rename_libarian_library_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='gst',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
