# Generated by Django 4.1.4 on 2023-02-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_library_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
