# Generated by Django 4.1.4 on 2023-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
            preserve_default=False,
        ),
    ]
