# Generated by Django 4.1.4 on 2023-02-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dj_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
