# Generated by Django 4.1.4 on 2023-02-17 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_alter_member_dj_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(default='2022-12-12'),
            preserve_default=False,
        ),
    ]
