# Generated by Django 4.1.4 on 2023-02-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_alter_member_address_alter_member_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sleeve_and_label',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
