# Generated by Django 4.1.4 on 2023-02-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_member_sleeve_and_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='currency',
            field=models.CharField(default='NZD', max_length=20),
            preserve_default=False,
        ),
    ]
