# Generated by Django 4.1.4 on 2023-02-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_library_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sleeve_and_label',
            field=models.BooleanField(default=False),
        ),
    ]
