# Generated by Django 4.1.4 on 2023-02-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_alter_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='c_o',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
