# Generated by Django 4.1.4 on 2023-03-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0057_member_no_mark_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='irrelevant_energy_level',
            field=models.ManyToManyField(related_name='irrelevant_energy_level', to='management.energylevel'),
        ),
        migrations.AddField(
            model_name='member',
            name='irrelevant_genres',
            field=models.ManyToManyField(related_name='irrelevant_genres', to='management.genre'),
        ),
        migrations.AddField(
            model_name='member',
            name='irrelevant_vibes',
            field=models.ManyToManyField(related_name='irrelevant_vibes', to='management.vibe'),
        ),
        migrations.AddField(
            model_name='member',
            name='prefered_energy_level',
            field=models.ManyToManyField(to='management.energylevel'),
        ),
        migrations.AddField(
            model_name='member',
            name='prefered_genres',
            field=models.ManyToManyField(to='management.genre'),
        ),
        migrations.AddField(
            model_name='member',
            name='prefered_vibes',
            field=models.ManyToManyField(to='management.vibe'),
        ),
    ]
