# Generated by Django 4.1.4 on 2023-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_member_irrelevant_energy_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='irrelevant_energy_level',
            field=models.ManyToManyField(blank=True, related_name='irrelevant_energy_level', to='management.energylevel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='irrelevant_genres',
            field=models.ManyToManyField(blank=True, related_name='irrelevant_genres', to='management.genre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='irrelevant_vibes',
            field=models.ManyToManyField(blank=True, related_name='irrelevant_vibes', to='management.vibe'),
        ),
        migrations.AlterField(
            model_name='member',
            name='prefered_energy_level',
            field=models.ManyToManyField(blank=True, to='management.energylevel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='prefered_genres',
            field=models.ManyToManyField(blank=True, to='management.genre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='prefered_vibes',
            field=models.ManyToManyField(blank=True, to='management.vibe'),
        ),
    ]
