# Generated by Django 4.1.4 on 2023-03-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_alter_member_irrelevant_energy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='discogs_page',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
