# Generated by Django 4.1.4 on 2023-03-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_member_discogs_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyldistributor',
            name='distributor_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
