# Generated by Django 4.1.4 on 2023-04-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_alter_vinyldistributor_weight_already_in_transit'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_library_shop',
            field=models.BooleanField(default=False),
        ),
    ]
