# Generated by Django 4.1.4 on 2023-06-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_member_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='island',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
