# Generated by Django 4.1.4 on 2023-10-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_address_island'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['membership_number']},
        ),
        migrations.AddField(
            model_name='vinyldistributor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
