# Generated by Django 4.1.4 on 2023-10-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0069_alter_member_options_vinyldistributor_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyldistributor',
            name='auto_update',
            field=models.BooleanField(default=True),
        ),
    ]
