# Generated by Django 4.1.4 on 2023-11-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_alter_vinyldistributor_auto_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='discogs_page',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dj_name',
        ),
        migrations.AlterField(
            model_name='member',
            name='account_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
