# Generated by Django 4.1.4 on 2023-11-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0072_remove_member_discogs_page_remove_member_dj_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_professional_service_provider',
            field=models.BooleanField(default=False),
        ),
    ]
