# Generated by Django 4.1.4 on 2023-11-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_member_is_professional_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='include_first_and_last_names',
            field=models.BooleanField(default=True),
        ),
    ]
