# Generated by Django 4.1.4 on 2023-11-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0074_address_include_first_and_last_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
