# Generated by Django 4.1.4 on 2023-11-21 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0075_member_gst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryShopBlockedLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=200, null=True)),
                ('member', models.ForeignKey(limit_choices_to={'is_library_shop': True}, on_delete=django.db.models.deletion.CASCADE, related_name='library_shop_blocked_labels_member', to='management.member')),
            ],
        ),
    ]
