# Generated by Django 4.1.4 on 2023-12-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_alter_libraryshopblockedlabels_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='no_mark_up',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sleeve_and_label',
        ),
    ]
