# Generated by Django 4.1.4 on 2023-12-17 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0078_remove_member_no_mark_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_of_the_librarian', to=settings.AUTH_USER_MODEL),
        ),
    ]
