# Generated by Django 4.1.4 on 2023-12-28 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0081_alter_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='librarian',
        ),
        migrations.AddField(
            model_name='library',
            name='library_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_library_shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
