# Generated by Django 4.1.4 on 2023-01-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0002_libraryplate_plate_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryplate',
            options={'ordering': ['related_vinyl_release__catalog_number', 'related_vinyl_plate__plate_index']},
        ),
    ]
