# Generated by Django 4.1.4 on 2023-01-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0003_alter_libraryplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryplate',
            name='cover',
            field=models.CharField(blank=True, choices=[('Inner Sleeve', 'Inner Sleeve'), ('Full Artwork', 'Full Artwork'), ('Record Label Sleeve', 'Record Label Sleeve'), ('Generic', 'Generic')], default='Inner Sleeve', max_length=100),
        ),
    ]
