# Generated by Django 4.1.4 on 2023-01-13 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0019_alter_vinyltrack_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vinylLibrary', '0007_remove_salevinyl_catalog_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryplate',
            options={'ordering': ['related_vinyl_plate']},
        ),
        migrations.RemoveField(
            model_name='libraryplate',
            name='library',
        ),
        migrations.RemoveField(
            model_name='libraryplate',
            name='plate_index',
        ),
        migrations.RemoveField(
            model_name='libraryplate',
            name='related_vinyl_release',
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='contributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='cover',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Inner Sleeve', 'Inner Sleeve'), ('Full Artwork', 'Full Artwork'), ('Top Sticker Artwork', 'Top Sticker Artwork'), ('Record Label Sleeve', 'Record Label Sleeve'), ('Generic', 'Generic')], default='Inner Sleeve', max_length=100),
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='media_condition',
            field=models.CharField(blank=True, choices=[('-', '-'), ('G', 'Good'), ('VG', 'Very Good'), ('VG+', 'Very Good Plus'), ('NM', 'Near Mint'), ('M', 'Mint')], max_length=20),
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='related_library_crate',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.PROTECT, related_name='related_library_plate', to='vinylLibrary.librarycrate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='related_vinyl_plate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='musicDatabase.vinylplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='release_type',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Full Release', 'Full Release'), ('White Label', 'White Label'), ('Stickered', 'Stickered')], default='Full Release', max_length=100),
        ),
    ]
