# Generated by Django 4.1.4 on 2023-01-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0008_alter_libraryplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='cover',
            field=models.CharField(blank=True, choices=[('Inner Sleeve', 'Inner Sleeve'), ('Full Artwork', 'Full Artwork'), ('Top Sticker Artwork', 'Top Sticker Artwork'), ('Record Label Sleeve', 'Record Label Sleeve'), ('Generic', 'Generic')], default='Inner Sleeve', max_length=100),
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='media_condition',
            field=models.CharField(blank=True, choices=[('G', 'Good'), ('VG', 'Very Good'), ('VG+', 'Very Good Plus'), ('NM', 'Near Mint'), ('M', 'Mint')], max_length=20),
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='release_type',
            field=models.CharField(blank=True, choices=[('Full Release', 'Full Release'), ('White Label', 'White Label'), ('Stickered', 'Stickered')], default='Full Release', max_length=100),
        ),
    ]
