# Generated by Django 4.1.4 on 2023-01-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0009_alter_libraryplate_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='cover',
            field=models.CharField(blank=True, choices=[('Inner Sleeve', 'Inner Sleeve'), ('Full Artwork', 'Full Artwork'), ('Top Sticker Artwork', 'Top Sticker Artwork'), ('Record Label Sleeve', 'Record Label Sleeve'), ('Plain', 'Plain')], default='Inner Sleeve', max_length=100),
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='plate_size',
            field=models.CharField(choices=[('12"', '12"'), ('10"', '10"'), ('7"', '7"')], default='12"', max_length=70),
        ),
    ]
