# Generated by Django 4.1.4 on 2023-01-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0014_rename_vinyl_color_libraryplate_vinyl_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryplate',
            name='vinyl_colour',
        ),
    ]
