# Generated by Django 4.1.4 on 2023-01-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0015_remove_libraryplate_vinyl_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryplate',
            name='vinyl_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue Marbled', 'Blue Marbled'), ('Blue Translucent', 'Blue Translucent'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Grey Marbled', 'Grey Marbled'), ('Magenta Translucent', 'Magenta Translucent'), ('Orange Translucent', 'Orange Translucent'), ('Purple Marbled', 'Purple Marbled'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White')], default='Black', max_length=100),
        ),
    ]
