# Generated by Django 4.1.4 on 2023-01-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_vinylcolour_options'),
        ('vinylLibrary', '0016_libraryplate_vinyl_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryplate',
            name='vinyl_colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.vinylcolour'),
        ),
    ]
