# Generated by Django 4.1.4 on 2023-01-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0017_libraryplate_vinyl_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryplate',
            name='vinyl_color',
        ),
    ]
