# Generated by Django 4.1.4 on 2023-01-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0018_remove_libraryplate_vinyl_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySubCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate_index_start', models.CharField(default='A', max_length=20)),
                ('crate_index_end', models.CharField(default='Z', max_length=20)),
                ('library_sub_crate_id', models.CharField(max_length=70)),
                ('issued', models.CharField(default='Available', max_length=20)),
                ('reserved', models.CharField(default='Available', max_length=12)),
                ('master_library_crate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinylLibrary.librarycrate')),
            ],
            options={
                'ordering': ['library_sub_crate_id'],
            },
        ),
    ]
