# Generated by Django 4.1.4 on 2023-01-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0019_librarysubcrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysubcrate',
            name='master_library_crate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_sub_crates', to='vinylLibrary.librarycrate'),
        ),
    ]
