# Generated by Django 4.1.4 on 2023-01-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0020_alter_librarysubcrate_master_library_crate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarycrate',
            name='crate_index_end',
        ),
        migrations.RemoveField(
            model_name='librarycrate',
            name='crate_index_start',
        ),
        migrations.RemoveField(
            model_name='librarycrate',
            name='issued',
        ),
        migrations.RemoveField(
            model_name='librarycrate',
            name='reserved',
        ),
    ]
