# Generated by Django 4.1.4 on 2023-01-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0021_remove_librarycrate_crate_index_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuecrate',
            old_name='library_crate',
            new_name='library_sub_crate',
        ),
    ]
