# Generated by Django 4.1.4 on 2023-01-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_profile_member'),
        ('vinylLibrary', '0022_rename_library_crate_issuecrate_library_sub_crate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecrate',
            name='membership_number',
        ),
        migrations.AddField(
            model_name='issuecrate',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuecrate',
            name='library_sub_crate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinylLibrary.librarysubcrate'),
        ),
    ]
