# Generated by Django 4.1.4 on 2023-01-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0023_remove_issuecrate_membership_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecrate',
            name='membership_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
