# Generated by Django 4.1.4 on 2023-01-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0024_issuecrate_membership_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuecrate',
            name='membership_number',
        ),
    ]
