# Generated by Django 4.1.4 on 2023-01-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0025_remove_issuecrate_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecrate',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='librarysubcrate',
            name='issued',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Available', 'Available')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='librarysubcrate',
            name='reserved',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Available', 'Available')], default='Available', max_length=12),
        ),
    ]
