# Generated by Django 4.1.4 on 2023-01-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_profile_member'),
        ('vinylLibrary', '0026_issuecrate_status_alter_librarysubcrate_issued_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueCrate',
            new_name='CrateIssue',
        ),
    ]
