# Generated by Django 4.1.4 on 2023-01-14 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0027_rename_issuecrate_crateissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='crateissue',
            name='date_time_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
