# Generated by Django 4.1.4 on 2023-01-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0028_crateissue_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crateissue',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
