# Generated by Django 4.1.4 on 2023-01-16 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_vinylindex'),
        ('vinylLibrary', '0029_alter_crateissue_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.member'),
        ),
    ]
