# Generated by Django 4.1.4 on 2023-01-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0030_alter_libraryplate_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycrate',
            name='library_crate_id',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='librarysubcrate',
            name='library_sub_crate_id',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
