# Generated by Django 4.1.4 on 2023-01-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_rename_cratevariations_cratevariation'),
        ('vinylLibrary', '0032_wantlistplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantlistCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wantlist_crate_id', models.CharField(max_length=70, unique=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.library')),
                ('related_crate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.crate')),
            ],
            options={
                'ordering': ['wantlist_crate_id'],
            },
        ),
    ]
