# Generated by Django 4.1.4 on 2023-01-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0033_wantlistcrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantlistplate',
            name='related_wantlist_crate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='related_wantlist_plate', to='vinylLibrary.wantlistcrate'),
            preserve_default=False,
        ),
    ]
