# Generated by Django 4.1.4 on 2023-01-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0034_wantlistplate_related_wantlist_crate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WantlistPlate',
        ),
    ]
