# Generated by Django 4.1.4 on 2023-01-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0036_wantlistplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryplate',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='static/vinylLibrary/libraryPlatesBarcodes'),
        ),
    ]
