# Generated by Django 4.1.4 on 2023-01-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0038_librarysubcrate_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycrate',
            name='crate_type',
            field=models.CharField(default='Mix', max_length=70),
            preserve_default=False,
        ),
    ]
