# Generated by Django 4.1.4 on 2023-01-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0039_librarycrate_crate_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarysubcrate',
            options={'ordering': ['sub_crate_id']},
        ),
        migrations.RenameField(
            model_name='crateissue',
            old_name='library_sub_crate',
            new_name='sub_crate',
        ),
        migrations.RenameField(
            model_name='librarysubcrate',
            old_name='library_sub_crate_id',
            new_name='sub_crate_id',
        ),
        migrations.AlterField(
            model_name='librarysubcrate',
            name='master_library_crate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_crates', to='vinylLibrary.librarycrate'),
        ),
    ]
