# Generated by Django 4.1.4 on 2023-01-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0040_alter_librarysubcrate_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibrarySubCrate',
            new_name='SubCrate',
        ),
    ]
