# Generated by Django 4.1.4 on 2023-01-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0041_rename_librarysubcrate_subcrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salevinyl',
            name='library',
        ),
        migrations.RemoveField(
            model_name='salevinyl',
            name='related_release',
        ),
        migrations.DeleteModel(
            name='LibraryShopItem',
        ),
        migrations.DeleteModel(
            name='SaleVinyl',
        ),
    ]
