# Generated by Django 4.1.4 on 2023-01-28 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_currency'),

        ('vinylLibrary', '0042_remove_salevinyl_library_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySaleVinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.library')),
                ('related_sale_vinyl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_library_sale_vinyl', to='shop.salevinyl')),
            ],
        ),
    ]
