# Generated by Django 4.1.4 on 2023-01-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0043_librarysalevinyl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibrarySaleVinyl',
        ),
    ]
