# Generated by Django 4.1.4 on 2023-01-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_vinyldistributor'),
        ('musicDatabase', '0037_vinylrelease_cost_price_and_more'),
        ('vinylLibrary', '0044_delete_librarysalevinyl'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySaleVinyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField()),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.library')),
                ('related_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_library_sale_vinyl', to='musicDatabase.vinylrelease')),
            ],
        ),
    ]
