# Generated by Django 4.1.4 on 2023-01-31 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0040_vinylrelease_sale_price_nz_and_more'),
        ('vinylLibrary', '0046_alter_librarysalevinyl_related_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarysalevinyl',
            name='related_release',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='related_library_sale_vinyl', to='musicDatabase.vinylrelease'),
        ),
    ]
