# Generated by Django 4.1.4 on 2023-02-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0050_lineitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='librarysalevinyl',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
