# Generated by Django 4.1.4 on 2023-02-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0053_subcrate_plate_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcrate',
            name='crate_type',
            field=models.CharField(default='Mix', max_length=70),
            preserve_default=False,
        ),
    ]
