# Generated by Django 4.1.4 on 2023-02-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0054_subcrate_crate_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryplate',
            old_name='related_member_crate',
            new_name='related_sub_crate',
        ),
    ]
