# Generated by Django 4.1.4 on 2023-02-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_library_gst'),
        ('vinylLibrary', '0055_rename_related_member_crate_libraryplate_related_sub_crate'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryplate',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.library'),
            preserve_default=False,
        ),
    ]
