# Generated by Django 4.1.4 on 2023-02-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0056_libraryplate_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryplate',
            name='library',
        ),
    ]
