# Generated by Django 4.1.4 on 2023-02-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0057_remove_libraryplate_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryplate',
            name='date_time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
