# Generated by Django 4.1.4 on 2023-02-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0058_libraryplate_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
