# Generated by Django 4.1.4 on 2023-02-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0059_alter_libraryplate_date_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantlistplate',
            name='related_vinyl_plate',
        ),
        migrations.RemoveField(
            model_name='wantlistplate',
            name='related_wantlist_crate',
        ),
        migrations.DeleteModel(
            name='WantlistCrate',
        ),
        migrations.DeleteModel(
            name='WantlistPlate',
        ),
    ]
