# Generated by Django 4.1.4 on 2023-02-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0061_remove_libraryplate_vinyl_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryplate',
            name='vinyl_colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
