# Generated by Django 4.1.4 on 2023-02-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0062_libraryplate_vinyl_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='cover',
            field=models.CharField(blank=True, choices=[('Inner Sleeve', 'Inner Sleeve'), ('Full Artwork', 'Full Artwork'), ('Top Sticker Artwork', 'Top Sticker Artwork'), ('Record Label Sleeve', 'Record Label Sleeve'), ('Plain', 'Plain')], max_length=100),
        ),
        migrations.AlterField(
            model_name='libraryplate',
            name='plate_size',
            field=models.CharField(choices=[('12"', '12"'), ('10"', '10"'), ('7"', '7"')], max_length=70),
        ),
    ]
