# Generated by Django 4.1.4 on 2023-02-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0063_alter_libraryplate_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryplate',
            name='release_type',
            field=models.CharField(blank=True, choices=[('Full Release', 'Full Release'), ('White Label', 'White Label'), ('Stickered', 'Stickered')], max_length=100),
        ),
    ]
