# Generated by Django 4.1.4 on 2023-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0065_libraryplate_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryplate',
            name='paid_for',
            field=models.BooleanField(default=True),
        ),
    ]
