# Generated by Django 4.1.4 on 2023-12-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0081_alter_member_user'),
        ('vinylLibrary', '0067_alter_libraryplate_paid_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='librarian_library', to='management.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='librarian_member', to='management.member')),
            ],
            options={
                'ordering': ['library', 'member'],
            },
        ),
    ]
