# Generated by Django 4.1.4 on 2023-12-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0069_libraryshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryShop',
        ),
    ]
