# Generated by Django 4.1.4 on 2023-12-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylLibrary', '0070_delete_libraryshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibrarySaleVinyl',
        ),
    ]
