# Generated by Django 4.1.4 on 2023-12-31 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0083_vinylcondition_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrateGrandParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('energy_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_crate_energy_level', to='management.energylevel')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_crate_genre', to='management.genre')),
                ('vibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_crate_vibe', to='management.vibe')),
            ],
            options={
                'ordering': ['genre', 'vibe', 'energy_level'],
            },
        ),
        migrations.CreateModel(
            name='CrateParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('crate_grand_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crate_grand_parent_crate_parent', to='crateBuilder.crategrandparent')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crate_parent_member', to='management.member')),
            ],
            options={
                'ordering': ['member', 'crate_grand_parent'],
            },
        ),
        migrations.CreateModel(
            name='CrateChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_start', models.CharField(default='0', max_length=1)),
                ('index_end', models.CharField(default='Z', max_length=1)),
                ('crate_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crate_crate_parent', to='crateBuilder.crateparent')),
            ],
            options={
                'ordering': ['crate_parent', 'index_start'],
            },
        ),
    ]
