# Generated by Django 4.1.4 on 2023-01-05 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('logo', models.FileField(blank=True, upload_to='static/musicDatabse/labelLogo')),
                ('country', models.CharField(choices=[('UK', 'UK'), ('BELGIUM', 'Belgium'), ('CANADA', 'Canada'), ('ESTONIA', 'Estonia'), ('FINLAND', 'Finland'), ('GERMANY', 'Germany'), ('IRELAND', 'Ireland'), ('NETHERLANDS', 'Netherlands'), ('NZ', 'NZ'), ('USA', 'USA')], default='UK', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VinylPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_index', models.CharField(choices=[('a/b', 'a/b'), ('c/d', 'c/d'), ('e/f', 'e/f'), ('g/h', 'g/h'), ('i/j', 'i/j'), ('k/l', 'k/l'), ('m/n', 'm/n'), ('o/p', 'o/p'), ('q/r', 'q/r'), ('s/t', 's/t'), ('u/v', 'u/v'), ('w/x', 'w/x'), ('y/z', 'y/z'), ('x/y', 'x,y'), ('xx/yy', 'xx/yy'), ('a/c', 'a/c')], default='a/b', max_length=20)),
            ],
            options={
                'ordering': ['related_vinyl_release__catalog_number', 'plate_index'],
            },
        ),
        migrations.CreateModel(
            name='VinylRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='static/musicDatabase/releaseArtwork')),
                ('catalog_number', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('UK', 'UK'), ('BELGIUM', 'Belgium'), ('CANADA', 'Canada'), ('ESTONIA', 'Estonia'), ('FINLAND', 'Finland'), ('GERMANY', 'Germany'), ('IRELAND', 'Ireland'), ('NETHERLANDS', 'Netherlands'), ('NZ', 'NZ'), ('USA', 'USA')], default='UK', max_length=20)),
                ('label', models.CharField(max_length=70)),
                ('plate_size', models.CharField(choices=[('12"', '12 Inch'), ('10"', '10 Inch'), ('7"', '7 Inch')], default='12"', max_length=70)),
                ('plate_count', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('eleven', '11'), ('twelve', '12'), ('thirteen', '13'), ('fourteen', '14'), ('fifteen', '15'), ('sixteen', '16'), ('seventeen', '17'), ('eighteen', '18'), ('ninteen', '19'), ('twenty', '20')], max_length=20)),
                ('track_count', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('eleven', '11'), ('twelve', '12'), ('thirteen', '13'), ('fourteen', '14'), ('fifteen', '15'), ('sixteen', '16'), ('seventeen', '17'), ('eighteen', '18'), ('ninteen', '19'), ('twenty', '20')], max_length=20)),
                ('release_format', models.CharField(max_length=200)),
                ('release_year', models.CharField(max_length=50)),
                ('release_title', models.CharField(max_length=100)),
                ('release_type', multiselectfield.db.fields.MultiSelectField(choices=[('Full Release', 'Full Release'), ('Full Release, Etched', 'Full Release, Etched'), ('Test Pressing', 'Test Pressing'), ('White Label', 'White Label'), ('Promo With Label', 'Promo With Label'), ('Promo, Label Sticker', 'Promo, Label Sticker'), ('White Label, Stickered', 'White Label, Stickered'), ('White Label, Stickered & Label Sticker', 'White Label, Stickered & Label Sticker'), ('White Label, Stamped', 'White Label, Stamped'), ('White Label, Stickered & Stamped', 'White Label, Stickered & Stamped'), ('Check', 'Check')], max_length=100)),
                ('vinyl_color', models.CharField(choices=[('Black', 'Black'), ('Blue Marbled', 'Blue Marbled'), ('Blue Translucent', 'Blue Translucent'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Grey Marbled', 'Grey Marbled'), ('Magenta Translucent', 'Magenta Translucent'), ('Orange Translucent', 'Orange Translucent'), ('Purple Marbled', 'Purple Marbled'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White')], default='Black', max_length=100)),
            ],
            options={
                'ordering': ['catalog_number'],
            },
        ),
        migrations.CreateModel(
            name='VinylTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('remixer', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=128)),
                ('index', models.CharField(max_length=5)),
                ('audio', models.FileField(blank=True, upload_to='static/musicDatabase/trackAudioClips')),
                ('bpm', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, choices=[('-', '-'), ('DNB', 'DNB'), ('Jungle 94-00', 'Jungle 94-00'), ('Jungle 10-', 'Jungle 10-'), ('Dubstep', 'Dubstep'), ('Grime', 'Grime'), ('Liquid DNB', 'Liquid DNB'), ('Neurofunk 04-', 'NeuroFunk 04-'), ('Neurofunk 98-03', 'NeuroFunk 98-03'), ('Minimal DNB', 'Minimal DNB'), ('Halftime', 'Halftime')], default='-', max_length=50)),
                ('vibe', models.CharField(blank=True, choices=[('-', '-'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green')], default='-', max_length=20)),
                ('energy_level', models.CharField(blank=True, choices=[('-', '-'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], default='-', max_length=10)),
                ('related_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musicDatabase.vinylrelease')),
                ('related_vinyl_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musicDatabase.vinylplate')),
            ],
            options={
                'ordering': ['related_release__catalog_number', 'index'],
            },
        ),
        migrations.AddField(
            model_name='vinylplate',
            name='related_vinyl_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='musicDatabase.vinylrelease'),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name_primary', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=2000)),
                ('photo', models.FileField(blank=True, upload_to='static/musicDatabse/artistProfileImage')),
                ('artist_is_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alias_title', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='musicDatabase.artist')),
            ],
        ),
    ]
