# Generated by Django 4.1.4 on 2023-01-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinylplate',
            options={'ordering': ['related_release__catalog_number', 'plate_index']},
        ),
        migrations.RenameField(
            model_name='vinylplate',
            old_name='related_vinyl_release',
            new_name='related_release',
        ),
    ]
