# Generated by Django 4.1.4 on 2023-01-05 21:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0004_alter_vinylplate_related_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full Release', 'Full Release'), ('Full Release & Etched', 'Full Release & Etched'), ('Test Pressing', 'Test Pressing'), ('White Label', 'White Label'), ('Promo With Label', 'Promo With Label'), ('Promo & Label Sticker', 'Promo & Label Sticker'), ('White Label & Stickered', 'White Label & Stickered'), ('White Label & Stickered & Label Sticker', 'White Label & Stickered & Label Sticker'), ('White Label & Stamped', 'White Label & Stamped'), ('White Label & Stickered & Stamped', 'White Label & Stickered & Stamped'), ('Check', 'Check')], max_length=100),
        ),
    ]
