# Generated by Django 4.1.4 on 2023-01-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0005_alter_vinylrelease_release_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
