# Generated by Django 4.1.4 on 2023-01-07 01:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0006_vinylrelease_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='release_month_year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full Release', 'Full Release'), ('Full Release & Etched', 'Full Release & Etched'), ('Test Pressing', 'Test Pressing'), ('White Label', 'White Label'), ('White Label Promo', 'White Label Promo'), ('White Label Test Pressing', 'White Label Test Pressing'), ('Promo With Label', 'Promo With Label'), ('Promo & Stickered', 'Promo & Stickered'), ('Promo & Label Sticker', 'Promo & Label Sticker'), ('White Label & Stickered', 'White Label & Stickered'), ('White Label & Stickered & Label Sticker', 'White Label & Stickered & Label Sticker'), ('White Label & Stamped', 'White Label & Stamped'), ('White Label & Stickered & Stamped', 'White Label & Stickered & Stamped'), ('Check', 'Check')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
