# Generated by Django 4.1.4 on 2023-01-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0007_vinylrelease_release_month_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinylrelease',
            name='release_month_year',
        ),
        migrations.AddField(
            model_name='vinylrelease',
            name='release_date_inaccurate',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=50),
        ),
    ]
