# Generated by Django 4.1.4 on 2023-01-08 08:24

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0009_vinylrelease_full_release_date_needs_to_be_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='label_profile',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='musicDatabase.label'),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='full_release_date_needs_to_be_found',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='label',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='plate_size',
            field=models.CharField(blank=True, choices=[('12"', '12 Inch'), ('10"', '10 Inch'), ('7"', '7 Inch')], default='12"', max_length=70),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_format',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Full Release', 'Full Release'), ('Full Release & Etched', 'Full Release & Etched'), ('Test Pressing', 'Test Pressing'), ('Test Pressing White Label', 'Test Pressing White Label'), ('White Label Test Pressing', 'White Label Test Pressing'), ('Test Pressing Stickered', 'Test Pressing Stickered'), ('Test Pressing Stamped', 'Test Pressing Stamped'), ('White Label', 'White Label'), ('White Label Promo', 'White Label Promo'), ('White Label & Stickered', 'White Label & Stickered'), ('White Label & Stickered & Label Sticker', 'White Label & Stickered & Label Sticker'), ('White Label & Stamped', 'White Label & Stamped'), ('White Label & Stickered & Stamped', 'White Label & Stickered & Stamped'), ('White Label Sampler', 'White Label Sampler'), ('Promo', 'Promo'), ('Promo With Label', 'Promo With Label'), ('Promo & Stickered', 'Promo & Stickered'), ('Promo Stickered with Label Sticker', 'Promo Stickered with Label Sticker'), ('Promo & Label Sticker', 'Promo & Label Sticker'), ('Picture Disc', 'Picture Disc'), ('Repress', 'Repress'), ('Check', 'Check')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='vinyl_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Blue Marbled', 'Blue Marbled'), ('Blue Translucent', 'Blue Translucent'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Grey Marbled', 'Grey Marbled'), ('Magenta Translucent', 'Magenta Translucent'), ('Orange Translucent', 'Orange Translucent'), ('Purple Marbled', 'Purple Marbled'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White')], default='Black', max_length=100),
        ),
    ]
