# Generated by Django 4.1.4 on 2023-01-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0011_remove_vinylrelease_full_release_date_needs_to_be_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='release_date_inaccurate_old',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_date_inaccurate',
            field=models.BooleanField(null=True),
        ),
    ]
