# Generated by Django 4.1.4 on 2023-01-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0012_vinylrelease_release_date_inaccurate_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinylrelease',
            old_name='release_date_inaccurate_old',
            new_name='check_release_date',
        ),
    ]
