# Generated by Django 4.1.4 on 2023-01-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0013_rename_release_date_inaccurate_old_vinylrelease_check_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='plate_count',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('eleven', '11'), ('twelve', '12'), ('thirteen', '13'), ('fourteen', '14'), ('fifteen', '15'), ('sixteen', '16'), ('seventeen', '17'), ('eighteen', '18'), ('ninteen', '19'), ('twenty', '20')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='track_count',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('eleven', '11'), ('twelve', '12'), ('thirteen', '13'), ('fourteen', '14'), ('fifteen', '15'), ('sixteen', '16'), ('seventeen', '17'), ('eighteen', '18'), ('ninteen', '19'), ('twenty', '20')], default='2', max_length=20),
        ),
    ]
