# Generated by Django 4.1.4 on 2023-01-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0015_alter_vinylrelease_plate_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='country',
            field=models.CharField(choices=[('UK', 'UK'), ('BELGIUM', 'Belgium'), ('CANADA', 'Canada'), ('ESTONIA', 'Estonia'), ('FINLAND', 'Finland'), ('GERMANY', 'Germany'), ('IRELAND', 'Ireland'), ('NETHERLANDS', 'Netherlands'), ('NZ', 'NZ'), ('USA', 'USA'), ('OTHER', 'Other')], default='UK', max_length=20),
        ),
        migrations.AlterField(
            model_name='vinyltrack',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='static/musicDatabase/trackAudioClips'),
        ),
    ]
