# Generated by Django 4.1.4 on 2023-01-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0016_alter_vinylrelease_country_alter_vinyltrack_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylplate',
            name='related_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_vinyl_plate', to='musicDatabase.vinylrelease'),
        ),
        migrations.AlterField(
            model_name='vinyltrack',
            name='related_vinyl_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_vinyl_track', to='musicDatabase.vinylplate'),
        ),
    ]
