# Generated by Django 4.1.4 on 2023-01-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0018_alter_vinylrelease_catalog_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinyltrack',
            options={'ordering': ['related_vinyl_plate__related_release__catalog_number', 'index']},
        ),
        migrations.RemoveField(
            model_name='vinylrelease',
            name='plate_size',
        ),
        migrations.RemoveField(
            model_name='vinylrelease',
            name='release_format',
        ),
        migrations.RemoveField(
            model_name='vinylrelease',
            name='release_type',
        ),
        migrations.RemoveField(
            model_name='vinylrelease',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='vinylrelease',
            name='vinyl_color',
        ),
        migrations.RemoveField(
            model_name='vinyltrack',
            name='related_release',
        ),
        migrations.AddField(
            model_name='vinylrelease',
            name='release_date_confirmed',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=50),
        ),
    ]
