# Generated by Django 4.1.4 on 2023-01-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0019_alter_vinyltrack_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylColours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
