# Generated by Django 4.1.4 on 2023-01-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0020_vinylcolours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VinylColours',
        ),
    ]
