# Generated by Django 4.1.4 on 2023-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0021_delete_vinylcolours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyltrack',
            name='vibe',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Y', 'Yellow'), ('B', 'Blue'), ('R', 'Red'), ('G', 'Green')], default='-', max_length=20),
        ),
    ]
