# Generated by Django 4.1.4 on 2023-01-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0023_remove_vinylrelease_check_release_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyltrack',
            old_name='energy_level',
            new_name='energy_levels',
        ),
        migrations.RenameField(
            model_name='vinyltrack',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='vinyltrack',
            old_name='vibe',
            new_name='vibes',
        ),
    ]
