# Generated by Django 4.1.4 on 2023-01-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0024_rename_energy_level_vinyltrack_energy_levels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinyltrack',
            old_name='energy_levels',
            new_name='energy_level',
        ),
        migrations.RenameField(
            model_name='vinyltrack',
            old_name='genres',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='vinyltrack',
            old_name='vibes',
            new_name='vibe',
        ),
    ]
