# Generated by Django 4.1.4 on 2023-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0025_rename_energy_levels_vinyltrack_energy_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_date_confirmed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
    ]
