# Generated by Django 4.1.4 on 2023-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0029_alter_vinyltrack_energy_level_alter_vinyltrack_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyltrack',
            name='energy_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vinyltrack',
            name='key_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
