# Generated by Django 4.1.4 on 2023-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0030_alter_vinyltrack_energy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyltrack',
            name='crate_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
