# Generated by Django 4.1.4 on 2023-01-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0031_vinyltrack_crate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinyltrack',
            name='catergorization_final',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
