# Generated by Django 4.1.4 on 2023-01-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0032_vinyltrack_catergorization_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyltrack',
            name='catergorization_final',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
    ]
