# Generated by Django 4.1.4 on 2023-01-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0033_alter_vinyltrack_catergorization_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyltrack',
            name='catergorization_final',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vinyltrack',
            name='crate_id',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vinyltrack',
            name='energy_level',
            field=models.CharField(blank=True, default='-', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vinyltrack',
            name='genre',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vinyltrack',
            name='vibe',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
    ]
