# Generated by Django 4.1.4 on 2023-01-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        ('musicDatabase', '0034_alter_vinyltrack_catergorization_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinylrelease',
            name='for_sale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vinylrelease',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.supplier'),
        ),
    ]
