# Generated by Django 4.1.4 on 2023-01-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0035_vinylrelease_cost_price_vinylrelease_for_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinylrelease',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='vinylrelease',
            name='for_sale',
        ),
        migrations.RemoveField(
            model_name='vinylrelease',
            name='supplier',
        ),
    ]
