# Generated by Django 4.1.4 on 2023-01-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_vinyldistributor'),
        ('musicDatabase', '0036_remove_vinylrelease_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinylrelease',
            name='stock_estimation',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vinylrelease',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.vinyldistributor'),
        ),
    ]
