# Generated by Django 4.1.4 on 2023-01-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0039_alter_vinylrelease_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='sale_price_NZ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='stock_estimation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
