# Generated by Django 4.1.4 on 2023-02-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0040_vinylrelease_sale_price_nz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='plate_size',
            field=models.CharField(default='12"', max_length=20),
        ),
    ]
