# Generated by Django 4.1.4 on 2023-02-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0041_vinylrelease_plate_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='supplier_item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
