# Generated by Django 4.1.4 on 2023-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0044_alter_vinylplate_plate_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='country',
            field=models.CharField(blank=True, default='UK', max_length=20, null=True),
        ),
    ]
