# Generated by Django 4.1.4 on 2023-02-25 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_library_currency'),
        ('musicDatabase', '0047_rename_vinyl_color_vinylrelease_vinyl_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.vinyldistributor'),
        ),
    ]
