# Generated by Django 4.1.4 on 2023-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0048_alter_vinylrelease_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='is_repress',
            field=models.BooleanField(default=False),
        ),
    ]
