# Generated by Django 4.1.4 on 2023-02-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0049_vinylrelease_is_repress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='plate_count',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='track_count',
            field=models.CharField(blank=True, default='2', max_length=20, null=True),
        ),
    ]
