# Generated by Django 4.1.4 on 2023-02-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0050_alter_vinylrelease_plate_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='on_previous_weekly_release_sheet',
            field=models.BooleanField(default=False),
        ),
    ]
