# Generated by Django 4.1.4 on 2023-03-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0051_vinylrelease_on_previous_weekly_release_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
