# Generated by Django 4.1.4 on 2023-03-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0052_vinylrelease_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
