# Generated by Django 4.1.4 on 2023-03-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0053_alter_vinylrelease_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='no_markup_price_NZ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
