# Generated by Django 4.1.4 on 2023-03-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0054_vinylrelease_no_markup_price_nz'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='is_bundle',
            field=models.BooleanField(default=False),
        ),
    ]
