# Generated by Django 4.1.4 on 2023-03-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0055_vinylrelease_is_bundle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinylrelease',
            old_name='no_markup_price_NZ',
            new_name='no_mark_up_price_NZ',
        ),
    ]
