# Generated by Django 4.1.4 on 2023-03-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0056_rename_no_markup_price_nz_vinylrelease_no_mark_up_price_nz'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='crate_id',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='vinylrelease',
            name='not_all_catergorized',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
