# Generated by Django 4.1.4 on 2023-03-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0057_vinylrelease_crate_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinylrelease',
            name='crate_id',
        ),
    ]
