# Generated by Django 4.1.4 on 2023-03-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0058_remove_vinylrelease_crate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='plate_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
