# Generated by Django 4.1.4 on 2023-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0059_alter_vinylrelease_plate_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinylrelease',
            name='supplier_item_code',
        ),
        migrations.RemoveField(
            model_name='vinylrelease',
            name='track_count',
        ),
    ]
