# Generated by Django 4.1.4 on 2023-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0060_remove_vinylrelease_supplier_item_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinylrelease',
            name='sale_price_NZ',
        ),
        migrations.AlterField(
            model_name='vinylrelease',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
