# Generated by Django 4.1.4 on 2023-04-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0061_remove_vinylrelease_sale_price_nz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='check_stock_availibility',
            field=models.BooleanField(default=False),
        ),
    ]
