# Generated by Django 4.1.4 on 2023-04-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0062_vinylrelease_check_stock_availibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='finalized',
            field=models.BooleanField(default=True),
        ),
    ]
