# Generated by Django 4.1.4 on 2023-04-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0063_vinylrelease_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
