# Generated by Django 4.1.4 on 2023-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0066_vinylrelease_artwork_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='most_common',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
