# Generated by Django 4.1.4 on 2023-08-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0069_vinylrelease_back_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinylrelease',
            old_name='not_all_catergorized',
            new_name='not_all_categorized',
        ),
    ]
