# Generated by Django 4.1.4 on 2023-12-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0081_alter_member_user'),
        ('musicDatabase', '0072_alter_vinylrelease_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.vinyldistributor'),
        ),
    ]
