# Generated by Django 4.1.4 on 2023-12-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0081_alter_member_user'),
        ('musicDatabase', '0073_alter_vinylrelease_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylReleaseRepressRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinyl_release_repress_request_member', to='management.member')),
                ('vinyl_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinyl_release_repress_request_vinyl_release', to='musicDatabase.vinylrelease')),
            ],
            options={
                'ordering': ['vinyl_release', 'member'],
            },
        ),
    ]
