# Generated by Django 4.1.4 on 2024-02-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0075_alter_vinylreleaserepressrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='release_date_tbc',
            field=models.BooleanField(default=False),
        ),
    ]
