# Generated by Django 4.1.4 on 2024-02-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0076_vinylrelease_release_date_tbc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyltrack',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, max_length=100),
        ),
    ]
