# Generated by Django 4.1.4 on 2024-02-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0077_alter_vinyltrack_bpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyltrack',
            name='bpm',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
