# Generated by Django 4.1.4 on 2024-03-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0083_vinylcondition_name'),
        ('musicDatabase', '0079_alter_vinyltrack_bpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='master_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.genre'),
        ),
    ]
