# Generated by Django 4.1.4 on 2024-03-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0080_vinylrelease_master_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='not_black',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
