# Generated by Django 4.1.4 on 2024-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0082_vinylrelease_average_tracks_per_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='average_tracks_per_side',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
