# Generated by Django 4.1.4 on 2024-03-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0083_alter_vinylrelease_average_tracks_per_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinylrelease',
            name='average_tracks_per_side',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
