# Generated by Django 4.1.4 on 2024-03-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0084_alter_vinylrelease_average_tracks_per_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylrelease',
            name='average_tracks_per_side_is_above_2',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
