# Generated by Django 4.1.4 on 2023-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(default='ATP', max_length=3),
            preserve_default=False,
        ),
    ]
