# Generated by Django 4.1.4 on 2023-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankaccount_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetype',
            name='type_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
