# Generated by Django 4.1.4 on 2023-03-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invoicetype_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='gst_included',
            field=models.BooleanField(default=True),
        ),
    ]
