# Generated by Django 4.1.4 on 2023-03-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cashbookentry_gst_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='uploaded_invoice_01',
            field=models.FileField(blank=True, upload_to='static/vinylShop/cashFlowUploadedInvoices'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='uploaded_invoice_02',
            field=models.FileField(blank=True, upload_to='static/vinylShop/cashFlowUploadedInvoices'),
        ),
    ]
