# Generated by Django 4.1.4 on 2023-03-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cashbookentry_uploaded_invoice_01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='processing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
