# Generated by Django 4.1.4 on 2023-03-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cashbookentry_gst_should_be_included'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbookInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_invoice', models.FileField(blank=True, upload_to='static/vinylShop/cashFlowUploadedInvoices')),
                ('cashbook_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.cashbookentry')),
            ],
        ),
    ]
