# Generated by Django 4.1.4 on 2023-03-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_cashbookentry_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbookentry',
            name='uploaded_invoice',
        ),
        migrations.RemoveField(
            model_name='cashbookentry',
            name='uploaded_invoice_01',
        ),
        migrations.RemoveField(
            model_name='cashbookentry',
            name='uploaded_invoice_02',
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
