# Generated by Django 4.1.4 on 2023-03-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_cashbookentry_uploaded_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbookMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gst_filing_date', models.DateField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gst_return_filed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='cashbookinvoice',
            name='uploaded_invoice',
            field=models.FileField(blank=True, upload_to='static/accounts/cashFlowUploadedInvoices'),
        ),
    ]
