# Generated by Django 4.1.4 on 2023-03-27 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_alter_vinyldistributor_weight_already_in_transit'),
        ('accounts', '0011_cashbookmonth_alter_cashbookinvoice_uploaded_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookmonth',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.library'),
            preserve_default=False,
        ),
    ]
