# Generated by Django 4.1.4 on 2023-03-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_cashbookentry_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbookentry',
            options={'ordering': ['-reconciled', '-processing_date']},
        ),
        migrations.AddField(
            model_name='invoicetype',
            name='is_expense',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoicetype',
            name='type_code',
            field=models.CharField(max_length=10),
        ),
    ]
