# Generated by Django 4.1.4 on 2023-03-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_cashbookentry_options_invoicetype_is_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetype',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000),
            preserve_default=False,
        ),
    ]
