# Generated by Django 4.1.4 on 2023-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_cashbookmonth_bank_fee_forcast_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbookmonth',
            old_name='opening_balance',
            new_name='opening_balance_actual',
        ),
        migrations.AddField(
            model_name='cashbookmonth',
            name='opening_balance_forcast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
