# Generated by Django 4.1.4 on 2023-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_opening_balance_cashbookmonth_opening_balance_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookmonth',
            name='gst_received_forcast',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
