# Generated by Django 4.1.4 on 2023-04-10 18:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_cashbookmonth_funds_introduced_forcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookmonth',
            name='opening_balance_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashbookmonth',
            name='opening_balance_forcast',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
