# Generated by Django 4.1.4 on 2023-04-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_bank_fee_forcast_cashbookmonth_bank_fee_forecast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookmonth',
            name='details',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
