# Generated by Django 4.1.4 on 2023-04-11 04:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_cashbookmonth_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookmonth',
            name='logistics_forecast',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
