# Generated by Django 4.1.4 on 2023-06-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_orderrequest_orderrequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
