# Generated by Django 4.1.4 on 2023-06-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_orderrequestitem_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='stockpiled',
            field=models.BooleanField(default=False),
        ),
    ]
