# Generated by Django 4.1.4 on 2023-06-20 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_member_active'),
        ('accounts', '0030_orderrequestitem_invoiced'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items__invoice+', to='accounts.orderrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.member')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
