# Generated by Django 4.1.4 on 2023-06-20 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='order_request_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items__invoice+', to='accounts.invoice'),
        ),
    ]
