# Generated by Django 4.1.4 on 2023-06-20 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_member_active'),
        ('accounts', '0034_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice__shipment+', to='accounts.orderrequestitem'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_NZD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracking_number', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('all_invoices_paid', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.vinyldistributor')),
            ],
        ),
    ]
