# Generated by Django 4.1.4 on 2023-06-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_invoice_shipment_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
