# Generated by Django 4.1.4 on 2023-06-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_shipment_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
