# Generated by Django 4.1.4 on 2023-06-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_shipment_received_alter_shipment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
