# Generated by Django 4.1.4 on 2023-06-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_member_active'),
        ('accounts', '0038_shipment_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.library'),
            preserve_default=False,
        ),
    ]
