# Generated by Django 4.1.4 on 2023-06-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_shipment_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice__shipment+', to='accounts.shipment'),
        ),
    ]
