# Generated by Django 4.1.4 on 2023-06-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice__shipment+', to='accounts.shipment'),
        ),
    ]
