# Generated by Django 4.1.4 on 2023-06-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_invoice_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='all_invoices_paid',
        ),
    ]
