# Generated by Django 4.1.4 on 2023-06-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_remove_shipment_all_invoices_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='order_request_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items_invoice', to='accounts.orderrequestitem'),
        ),
    ]
