# Generated by Django 4.1.4 on 2023-06-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_invoiceitem_order_request_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
