# Generated by Django 4.1.4 on 2023-06-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_shipment_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='en_route',
            field=models.BooleanField(default=False),
        ),
    ]
