# Generated by Django 4.1.4 on 2023-06-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_address_island'),
        ('accounts', '0047_orderrequestitem_delivered_orderrequestitem_en_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('received', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_package_member', to='management.member')),
            ],
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='courier_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_request_item_courier_package', to='accounts.courierpackage'),
        ),
    ]
