# Generated by Django 4.1.4 on 2023-06-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_courierpackage_orderrequestitem_courier_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierpackage',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
