# Generated by Django 4.1.4 on 2023-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_courierpackage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierpackage',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
