# Generated by Django 4.1.4 on 2023-06-24 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_courierpackage_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='in_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_shipment', to='accounts.shipment'),
        ),
    ]
