# Generated by Django 4.1.4 on 2023-06-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_courierpackage_en_route_courierpackage_invoiced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierpackage',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
