# Generated by Django 4.1.4 on 2023-06-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_address_island'),
        ('musicDatabase', '0067_vinylrelease_most_common'),
        ('accounts', '0053_courierpackage_packed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.library')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('filled', models.BooleanField(default=False)),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items__order_request+', to='accounts.purchaseorderrequest')),
                ('vinyl_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items__vinyl_release+', to='musicDatabase.vinylrelease')),
            ],
        ),
    ]
