# Generated by Django 4.1.4 on 2023-06-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_address_island'),
        ('accounts', '0054_purchaseorderrequest_purchaseorderrequestitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderrequestitem',
            name='order_request',
        ),
        migrations.AddField(
            model_name='purchaseorderrequest',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.vinyldistributor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderrequestitem',
            name='purchase_order_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_request_item_purchase_order_request', to='accounts.purchaseorderrequest'),
            preserve_default=False,
        ),
    ]
