# Generated by Django 4.1.4 on 2023-06-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_remove_purchaseorderrequestitem_order_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='purchase_order_request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_request_item_purchase_order_request_item', to='accounts.purchaseorderrequestitem'),
        ),
    ]
