# Generated by Django 4.1.4 on 2023-06-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_orderrequestitem_purchase_order_request_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderrequestitem',
            old_name='quantity',
            new_name='quantity_old',
        ),
    ]
