# Generated by Django 4.1.4 on 2023-06-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_rename_quantity_purchaseorderrequestitem_quantity_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
