# Generated by Django 4.1.4 on 2023-06-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_orderrequestitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
