# Generated by Django 4.1.4 on 2023-06-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_orderrequestitem_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='consolidated_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidated_shipment_shipment', to='accounts.shipment'),
        ),
    ]
