# Generated by Django 4.1.4 on 2023-06-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_shipment_consolidated_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='consolidated_shipment',
        ),
    ]
