# Generated by Django 4.1.4 on 2023-06-28 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_address_island'),
        ('accounts', '0061_remove_shipment_consolidated_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='consolidated_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidated_shipment_shipment', to='accounts.shipment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='consolidation_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_location_shipment', to='management.vinyldistributor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_consolidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_shipment', to='management.vinyldistributor'),
        ),
    ]
