# Generated by Django 4.1.4 on 2023-06-28 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_address_island'),
        ('accounts', '0062_shipment_consolidated_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='consolidation_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consolidation_location_shipment', to='management.vinyldistributor'),
        ),
    ]
