# Generated by Django 4.1.4 on 2023-06-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_shipment_consolidation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='arrived_at_consolidation_location',
            field=models.BooleanField(default=False),
        ),
    ]
