# Generated by Django 4.1.4 on 2023-08-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_invoice_consolidated_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
