# Generated by Django 4.1.4 on 2023-08-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_invoiceitem_flattened_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='flattened_shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
