# Generated by Django 4.1.4 on 2023-08-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_invoice_flattened_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='flattened',
            field=models.BooleanField(default=False),
        ),
    ]
