# Generated by Django 4.1.4 on 2023-08-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_invoice_flattened'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
