# Generated by Django 4.1.4 on 2023-08-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_invoice_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='flattened_consolidated_shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
