# Generated by Django 4.1.4 on 2023-08-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_invoice_flattened_consolidated_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='date_when_set_to_unavailable',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
