# Generated by Django 4.1.4 on 2023-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_orderrequestitem_date_when_set_to_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pseudo_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
