# Generated by Django 4.1.4 on 2023-08-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_invoice_pseudo_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pseudo_invoice_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
