# Generated by Django 4.1.4 on 2023-08-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_invoice_pseudo_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='direct_shopping_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
