# Generated by Django 4.1.4 on 2023-10-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_invoice_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
