# Generated by Django 4.1.4 on 2023-11-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_shipment_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_hour_invoice', to='accounts.invoice')),
                ('invoice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.invoicetype')),
            ],
        ),
    ]
