# Generated by Django 4.1.4 on 2023-11-10 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0072_remove_member_discogs_page_remove_member_dj_name_and_more'),
        ('accounts', '0079_invoicehour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.address')),
            ],
        ),
        migrations.RenameModel(
            old_name='InvoiceHour',
            new_name='ProfessionalServicesInvoiceHour',
        ),
        migrations.CreateModel(
            name='ProfessionalServicesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=1000, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.member')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
