# Generated by Django 4.1.4 on 2023-11-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalservicesinvoicehour',
            name='hourly_fee',
        ),
        migrations.AlterField(
            model_name='professionalservicesinvoice',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='professionalservicesinvoicehour',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_hour_invoice', to='accounts.professionalservicesinvoice'),
        ),
        migrations.CreateModel(
            name='ProfessionalServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('fee_nzd', models.PositiveIntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='professionalservicesinvoicehour',
            name='invoice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professionalservicetype'),
        ),
    ]
