# Generated by Django 4.1.4 on 2023-11-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_remove_professionalservicesinvoicehour_hourly_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalservicetype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
