# Generated by Django 4.1.4 on 2023-11-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_member_is_professional_service_provider'),
        ('accounts', '0082_alter_professionalservicetype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalservicesinvoice',
            name='member',
        ),
        migrations.AddField(
            model_name='professionalservicesinvoice',
            name='service_provider',
            field=models.ForeignKey(default=1, limit_choices_to={'is_service_provider': True}, on_delete=django.db.models.deletion.PROTECT, to='management.member'),
            preserve_default=False,
        ),
    ]
