# Generated by Django 4.1.4 on 2023-11-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_member_is_professional_service_provider'),
        ('accounts', '0083_remove_professionalservicesinvoice_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalservicesinvoice',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to={'is_service_provider': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.member'),
        ),
    ]
