# Generated by Django 4.1.4 on 2023-11-10 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_member_is_professional_service_provider'),
        ('accounts', '0084_alter_professionalservicesinvoice_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalservicesinvoice',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='professionalservicesinvoice',
            name='service_provider',
            field=models.ForeignKey(limit_choices_to={'is_professional_service_provider': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.member'),
        ),
        migrations.AlterField(
            model_name='professionalservicetype',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
