# Generated by Django 4.1.4 on 2023-11-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_alter_professionalservicesinvoice_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalservicesinvoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='professionalservicesinvoice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='professionalservicesinvoicehour',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='professionalservicesinvoicehour',
            name='invoice_type',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ProfessionalServicesInvoice',
        ),
        migrations.DeleteModel(
            name='ProfessionalServicesInvoiceHour',
        ),
        migrations.DeleteModel(
            name='ProfessionalServiceType',
        ),
    ]
