# Generated by Django 4.1.4 on 2023-11-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_alter_bankaccount_account_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='to_direct_shopping_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
