# Generated by Django 4.1.4 on 2023-12-15 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_remove_member_no_mark_up_and_more'),
        ('accounts', '0088_orderrequestitem_to_direct_shopping_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='shop_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_request_member', to='management.member'),
        ),
        migrations.AlterField(
            model_name='orderrequestitem',
            name='order_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items_order_request', to='accounts.orderrequest'),
        ),
    ]
