# Generated by Django 4.1.4 on 2023-12-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_orderrequestitem_shop_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='hidden_from_member',
            field=models.BooleanField(default=False),
        ),
    ]
