# Generated by Django 4.1.4 on 2023-12-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_orderrequestitem_hidden_from_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='member_archived',
            field=models.BooleanField(default=False),
        ),
    ]
