# Generated by Django 4.1.4 on 2023-12-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_invoice_member_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
