# Generated by Django 4.1.4 on 2023-12-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_orderrequestitem_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='check_availability',
            field=models.BooleanField(default=False),
        ),
    ]
