# Generated by Django 4.1.4 on 2023-12-17 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_remove_member_no_mark_up_and_more'),
        ('accounts', '0093_orderrequestitem_check_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.library'),
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_request_item_member', to='management.member'),
        ),
    ]
