# Generated by Django 4.1.4 on 2023-12-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_alter_orderrequestitem_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequestitem',
            name='order_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_request_items_order_request', to='accounts.orderrequest'),
        ),
    ]
