# Generated by Django 4.1.4 on 2023-12-17 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0020_stockitem_quantity_incoming'),
        ('accounts', '0096_alter_orderrequestitem_order_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_request_item_stock_item', to='vinylShop.stockitem'),
        ),
        migrations.AlterField(
            model_name='orderrequestitem',
            name='order_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_request_items_order_request', to='accounts.orderrequest'),
        ),
    ]
