# Generated by Django 4.1.4 on 2023-12-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_orderrequestitem_stock_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='to_become_shop_stock',
            field=models.BooleanField(default=False),
        ),
    ]
