# Generated by Django 4.1.4 on 2023-12-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_orderrequestitem_to_become_shop_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='quantity_used_by_member',
            field=models.IntegerField(default=0),
        ),
    ]
