# Generated by Django 4.1.4 on 2023-12-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_orderrequestitem_quantity_used_by_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='flattened',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pseudo_invoice',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
