# Generated by Django 4.1.4 on 2023-12-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_alter_invoice_flattened_alter_invoice_pseudo_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='flattened_price',
            new_name='invoiced_sale_price',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoiced_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoiced_sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoiced_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
