# Generated by Django 4.1.4 on 2023-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_rename_flattened_price_invoiceitem_invoiced_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='consolidated_shipment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='direct_shopping_invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='flattened',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='flattened_consolidated_shipping_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='flattened_shipping_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pseudo_invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pseudo_invoice_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipment',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_shipping_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
