# Generated by Django 4.1.4 on 2023-12-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_remove_invoice_consolidated_shipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_total_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='member_has_received_all_plates',
            field=models.BooleanField(default=False),
        ),
    ]
