# Generated by Django 4.1.4 on 2023-12-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_invoice_invoice_total_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='member_has_made_payment',
            field=models.BooleanField(default=False),
        ),
    ]
