# Generated by Django 4.1.4 on 2023-11-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0073_member_is_professional_service_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_client', to='management.address')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalServicesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_service_invoice_client', to='professionalServices.client')),
                ('service_provider', models.ForeignKey(limit_choices_to={'is_professional_service_provider': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_service_invoice_service_provider', to='management.member')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProfessionalServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('fee_nzd', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProfessionalServicesInvoiceHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_hour_invoice', to='professionalServices.professionalservicesinvoice')),
                ('invoice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionalServices.professionalservicetype')),
            ],
        ),
    ]
