# Generated by Django 4.1.4 on 2023-11-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_member_is_professional_service_provider'),
        ('professionalServices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalServiceProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('fee_nzd', models.PositiveIntegerField()),
                ('professional_service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_service_provider_service_professional_service_type', to='professionalServices.professionalservicetype')),
                ('service_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_service_provider_service_service_provider', to='management.member')),
            ],
            options={
                'ordering': ('professional_service_type',),
            },
        ),
    ]
