# Generated by Django 4.1.4 on 2023-11-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0002_professionalserviceproviderservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalserviceproviderservice',
            name='notes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
