# Generated by Django 4.1.4 on 2023-11-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0003_alter_professionalserviceproviderservice_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalserviceproviderservice',
            old_name='notes',
            new_name='description',
        ),
    ]
