# Generated by Django 4.1.4 on 2023-11-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0004_rename_notes_professionalserviceproviderservice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalserviceproviderservice',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
