# Generated by Django 4.1.4 on 2023-11-10 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0005_alter_professionalserviceproviderservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservicesinvoicehour',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professionalServices.professionalserviceproviderservice'),
        ),
    ]
