# Generated by Django 4.1.4 on 2023-11-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0007_alter_professionalservicesinvoicehour_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalservicesinvoicehour',
            name='invoice_type',
        ),
        migrations.AlterField(
            model_name='professionalservicesinvoicehour',
            name='service_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'service_provider': 10}, null=True, on_delete=django.db.models.deletion.CASCADE, to='professionalServices.professionalserviceproviderservice'),
        ),
    ]
