# Generated by Django 4.1.4 on 2023-11-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0008_remove_professionalservicesinvoicehour_invoice_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalservicetype',
            name='fee_nzd',
        ),
    ]
