# Generated by Django 4.1.4 on 2023-11-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0009_remove_professionalservicetype_fee_nzd'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservicesinvoicehour',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='professionalservicesinvoice',
            constraint=models.UniqueConstraint(fields=('id', 'service_provider'), name='unique_id_service_provider_id'),
        ),
    ]
