# Generated by Django 4.1.4 on 2023-11-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0010_professionalservicesinvoicehour_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalservicesinvoicehour',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
