# Generated by Django 4.1.4 on 2023-11-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0013_alter_professionalservicesinvoicehour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservicesinvoicehour',
            name='notes',
            field=models.TextField(default='', max_length=200),
        ),
    ]
