# Generated by Django 4.1.4 on 2023-11-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0014_professionalservicesinvoicehour_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalservicesinvoicehour',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
