# Generated by Django 4.1.4 on 2023-12-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionalServices', '0016_alter_professionalservicesinvoicehour_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalservicesinvoice',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
