# Generated by Django 4.1.4 on 2023-02-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReleaseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField()),
                ('printable_release_sheet', models.FileField(blank=True, upload_to='static/vinylShop/weeklyReleaseSheet')),
            ],
            options={
                'ordering': ['-week_ending'],
            },
        ),
    ]
