# Generated by Django 4.1.4 on 2023-03-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyreleasesheet',
            options={'ordering': ['-search_end_date']},
        ),
        migrations.RenameField(
            model_name='weeklyreleasesheet',
            old_name='week_ending',
            new_name='search_end_date',
        ),
        migrations.AddField(
            model_name='weeklyreleasesheet',
            name='search_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
