# Generated by Django 4.1.4 on 2023-03-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0002_alter_weeklyreleasesheet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreleasesheet',
            name='search_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
