# Generated by Django 4.1.4 on 2023-03-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0003_alter_weeklyreleasesheet_search_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreleasesheet',
            name='release_sheet_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
