# Generated by Django 4.1.4 on 2023-03-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0005_bankaccount_invoicetype_cashbookentry'),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='bankaccount',
                    name='account_name',
                    field=models.ForeignKey(on_delete=models.deletion.PROTECT, to='vinylShop.BankAccount'),
                ),
            ],
            # You're reusing an existing table, so do nothing
            database_operations=[],
        ),

    
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='bankaccount',
                    name='account_number',
                    field=models.ForeignKey(on_delete=models.deletion.PROTECT, to='vinylShop.BankAccount'),
                ),
            ],
            # You're reusing an existing table, so do nothing
            database_operations=[],
        ),

    ]
