# Generated by Django 4.1.4 on 2023-03-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0006_alter_bankaccount_account_name_and_more'),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='cashbookentry',
                    name='bank_account_used',
                ),
            ],
            database_operations=[],
        ),


        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='cashbookentry',
                    name='invoice_type',
                ),
            ],
            database_operations=[],
        ),


        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CashBookEntry',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='CashBookEntry',
                    table='accounts_cashbookentry',
                ),
            ],
        ),
        

        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='BankAccount',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='BankAccount',
                    table='accounts_bankaccount',
                ),
            ],
        ),


        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='InvoiceType',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='InvoiceType',
                    table='accounts_invoicetype',
                ),
            ],
        ),

    ]
