# Generated by Django 4.1.4 on 2023-06-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0008_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
