# Generated by Django 4.1.4 on 2023-06-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0009_stockitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='release',
            new_name='vinyl_release',
        ),
    ]
