# Generated by Django 4.1.4 on 2023-06-25 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_address_island'),
        ('vinylShop', '0010_rename_release_stockitem_vinyl_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='member',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='price',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='management.library'),
            preserve_default=False,
        ),
    ]
