# Generated by Django 4.1.4 on 2023-11-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0012_stockitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='status',
            field=models.PositiveIntegerField(default=0, max_length=1),
        ),
    ]
