# Generated by Django 4.1.4 on 2023-12-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0014_alter_stockitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='quantity_incoming',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
