# Generated by Django 4.1.4 on 2023-12-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0015_stockitem_quantity_incoming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='quantity_incoming',
            new_name='quantity_incomingz',
        ),
    ]
