# Generated by Django 4.1.4 on 2023-12-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0016_rename_quantity_incoming_stockitem_quantity_incomingz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity_incomingz',
        ),
    ]
