# Generated by Django 4.1.4 on 2023-12-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0017_remove_stockitem_quantity_incomingz'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='auto_restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='auto_restock_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
