# Generated by Django 4.1.4 on 2023-12-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0019_rename_auto_restock_level_stockitem_auto_restock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='quantity_incoming',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
