# Generated by Django 4.1.4 on 2023-12-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0020_stockitem_quantity_incoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='quantity_incoming',
            field=models.IntegerField(default=0),
        ),
    ]
