# Generated by Django 4.1.4 on 2023-12-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0022_alter_stockitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='quantity_plus_quantity_incoming_stock',
            field=models.IntegerField(default=0),
        ),
    ]
