# Generated by Django 4.1.4 on 2023-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0023_stockitem_quantity_plus_quantity_incoming_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
