# Generated by Django 4.1.4 on 2023-12-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0024_alter_stockitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
