# Generated by Django 4.1.4 on 2023-12-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0028_alter_shopgenre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='added_by_member',
            field=models.BooleanField(default=False),
        ),
    ]
