# Generated by Django 4.1.4 on 2023-12-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0029_stockitem_added_by_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='has_an_outer_sleeve',
            field=models.BooleanField(default=False),
        ),
    ]
