# Generated by Django 4.1.4 on 2023-12-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0030_stockitem_has_an_outer_sleeve'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='updated_by_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
