# Generated by Django 4.1.4 on 2024-01-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0033_alter_shopgenre_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='updated_by_librarian',
            new_name='updated_by_library_shop',
        ),
    ]
