# Generated by Django 4.1.4 on 2024-02-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylShop', '0034_rename_updated_by_librarian_stockitem_updated_by_library_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='in_library_shop_want_list',
            field=models.BooleanField(default=False),
        ),
    ]
