# Generated by Django 4.1.4 on 2024-03-21 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0080_vinylrelease_master_genre'),
        ('vinylShop', '0035_stockitem_in_library_shop_want_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='vinyl_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinyl_release_stock_item', to='musicDatabase.vinylrelease'),
        ),
    ]
