# Generated by Django 4.1.4 on 2023-03-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicDatabase', '0056_rename_no_markup_price_nz_vinylrelease_no_mark_up_price_nz'),
        ('vinylLibrary', '0064_alter_libraryplate_release_type'),
        ('management', '0057_member_no_mark_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('mark_up_removed', models.BooleanField(default=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.member')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recieved', models.BooleanField(default=False)),
                ('library_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_lp', to='vinylLibrary.libraryplate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cart.order')),
                ('vinyl_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='musicDatabase.vinylrelease')),
            ],
        ),
    ]
