# Generated by Django 4.1.4 on 2023-03-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_orderitem_vinyl_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vinyl_release',
        ),
    ]
