# Generated by Django 4.1.4 on 2023-03-02 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0056_rename_no_markup_price_nz_vinylrelease_no_mark_up_price_nz'),
        ('cart', '0003_remove_orderitem_vinyl_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vinyl_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='musicDatabase.vinylrelease'),
        ),
    ]
