# Generated by Django 4.1.4 on 2023-03-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_on_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
