# Generated by Django 4.1.4 on 2023-03-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_credit_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='credit_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
