# Generated by Django 4.1.4 on 2023-03-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='mark_up_removed',
        ),
    ]
