# Generated by Django 4.1.4 on 2023-03-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_purchaseorder_mark_up_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
    ]
