# Generated by Django 4.1.4 on 2023-03-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
