# Generated by Django 4.1.4 on 2023-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_orderitem_ordered_purchaseorderitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
