# Generated by Django 4.1.4 on 2023-03-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_purchaseorder_funded'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='cashbook_entry_added',
            field=models.BooleanField(default=False),
        ),
    ]
