# Generated by Django 4.1.4 on 2023-04-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_purchaseorder_cashbook_entry_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
