# Generated by Django 4.1.4 on 2023-04-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_orderitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_restock',
            field=models.BooleanField(default=False),
        ),
    ]
