# Generated by Django 4.1.4 on 2023-04-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_purchaseorderitem_is_restock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='is_restock',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_restock',
            field=models.BooleanField(default=False),
        ),
    ]
