# Generated by Django 4.1.4 on 2023-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_remove_purchaseorderitem_is_restock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashbook_entry_added',
            field=models.BooleanField(default=False),
        ),
    ]
