# Generated by Django 4.1.4 on 2023-02-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnergyLevel',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Vibe',
        ),
        migrations.DeleteModel(
            name='VinylColour',
        ),
        migrations.DeleteModel(
            name='VinylCondition',
        ),
        migrations.DeleteModel(
            name='VinylIndex',
        ),
        migrations.DeleteModel(
            name='VinylPlateSize',
        ),
        migrations.DeleteModel(
            name='VinylReleaseType',
        ),
        migrations.DeleteModel(
            name='VinylSleeveType',
        ),
        migrations.AlterModelOptions(
            name='cratetype',
            options={'ordering': ['crate_type']},
        ),
        migrations.RemoveField(
            model_name='cratetype',
            name='variation',
        ),
        migrations.AddField(
            model_name='cratetype',
            name='crate_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
