# Generated by Django 4.1.4 on 2023-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_delete_energylevel_delete_genre_delete_vibe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['gender'],
            },
        ),
    ]
