# Generated by Django 4.1.4 on 2023-02-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vinylLibrary', '0051_alter_librarysalevinyl_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_crate_id', models.CharField(max_length=70, unique=True)),
                ('master_library_crate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_crates', to='vinylLibrary.librarycrate')),
            ],
            options={
                'ordering': ['member_crate_id'],
            },
        ),
    ]
