# Generated by Django 4.1.4 on 2023-02-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_alter_crate_genre'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercrate',
            name='member',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='management.member'),
            preserve_default=False,
        ),
    ]
