# Generated by Django 4.1.4 on 2023-02-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_alter_crate_genre'),
        ('members', '0002_membercrate_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercrate',
            name='related_crate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.crate'),
        ),
    ]
