# Generated by Django 4.1.4 on 2023-02-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_alter_crate_genre'),
        ('members', '0006_alter_membercrate_master_library_crate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercrate',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_crate', to='management.member'),
        ),
        migrations.AlterField(
            model_name='membercrate',
            name='related_crate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_crate', to='management.crate'),
        ),
    ]
