# Generated by Django 4.1.4 on 2023-02-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_membercrate_member_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberCrate',
        ),
    ]
