# Generated by Django 4.1.4 on 2023-04-02 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicDatabase', '0059_alter_vinylrelease_plate_count'),
        ('management', '0065_alter_vinyldistributor_weight_already_in_transit'),
        ('members', '0008_delete_membercrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberWantlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='management.member')),
                ('want_list', models.ManyToManyField(blank=True, related_name='member_want_list', to='musicDatabase.vinylrelease')),
            ],
        ),
    ]
