# Generated by Django 4.1.4 on 2023-04-24 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_member_is_library_shop'),
        ('musicDatabase', '0065_alter_vinylrelease_finalized'),
        ('members', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUnwantedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_unwanted', to='management.member')),
                ('unwanted_list', models.ManyToManyField(blank=True, related_name='member_unwanted_list', to='musicDatabase.vinylrelease')),
            ],
        ),
    ]
