# Generated by Django 4.1.4 on 2023-04-25 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicDatabase', '0065_alter_vinylrelease_finalized'),
        ('management', '0066_member_is_library_shop'),
        ('members', '0010_memberunwantedlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMaybeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maybe_list', models.ManyToManyField(blank=True, related_name='member_maybe_list', to='musicDatabase.vinylrelease')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_maybe', to='management.member')),
            ],
        ),
    ]
