# Generated by Django 4.1.4 on 2023-12-30 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0083_vinylcondition_name'),
        ('members', '0014_memberplate_plate_sleeve_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplate',
            name='vinyl_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.vinylcolour'),
        ),
    ]
