# Generated by Django 4.1.4 on 2023-12-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_memberplate_vinyl_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberplate',
            old_name='vinyl_color',
            new_name='vinyl_colour',
        ),
    ]
