# Generated by Django 4.1.4 on 2023-12-31 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crateBuilder', '0001_initial'),
        ('members', '0016_rename_vinyl_color_memberplate_vinyl_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplate',
            name='parent_crate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crateBuilder.crateparent'),
        ),
    ]
