# Generated by Django 4.1.4 on 2023-12-31 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_memberplate_parent_crate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberplate',
            old_name='parent_crate',
            new_name='crate_parent',
        ),
    ]
