# Generated by Django 4.1.4 on 2024-01-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_rename_parent_crate_memberplate_crate_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplate',
            name='crate_parent_desired_option',
            field=models.BooleanField(default=False),
        ),
    ]
