# Generated by Django 4.1.4 on 2024-01-04 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crateBuilder', '0001_initial'),
        ('members', '0019_memberplate_crate_parent_desired_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberplate',
            name='desired_crate_parent_option_crate_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_plate_desired_crate_parent_option_crate_parent', to='crateBuilder.crateparent'),
        ),
        migrations.AlterField(
            model_name='memberplate',
            name='crate_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_plate_crate_parent', to='crateBuilder.crateparent'),
        ),
    ]
